name: Brain Smells
favicon: null
layout_spectrum: 0.74023
typography_spectrum: 0.8981124206911772
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#273335'
    - '#abc7a7'
    - '#537855'
    - '#fed53f'
  brandStrength: 0.625
  lightness: 0.7873881249688566
  saturation: 0.5
  rhythmicContrast: 0.28077693516388535
purpose: []
